In [1]:
from tensorflow import keras
from keras.applications import VGG16
from keras.applications.vgg16 import preprocess_input
from load_data import as_numpy

In [2]:
# Load data as list of Numpy arrays
data = as_numpy("./PetImages", True)

/Users/shaun/miniforge3/envs/tensorflow/lib/python3.9/site-packages/PIL/TiffImagePlugin.py:822: UserWarning: Truncated File Read
  warnings.warn(str(msg))


Image loading completed...
Loaded 24998 images
Unable to load 4 images


In [3]:
# View first element of data
print(data[0])

[[[199. 169. 131.]
  [200. 170. 132.]
  [202. 172. 134.]
  ...
  [173. 121.  97.]
  [172. 120.  96.]
  [173. 119.  93.]]

 [[200. 170. 132.]
  [201. 171. 133.]
  [203. 173. 135.]
  ...
  [174. 122.  98.]
  [173. 121.  97.]
  [173. 119.  93.]]

 [[202. 172. 134.]
  [203. 173. 135.]
  [204. 174. 136.]
  ...
  [176. 124. 100.]
  [175. 123.  99.]
  [175. 121.  95.]]

 ...

 [[ 67.  52.  49.]
  [ 66.  51.  48.]
  [ 68.  54.  53.]
  ...
  [144. 174. 202.]
  [138. 172. 199.]
  [147. 180. 211.]]

 [[ 68.  53.  50.]
  [ 67.  52.  49.]
  [ 68.  54.  53.]
  ...
  [133. 163. 191.]
  [123. 157. 184.]
  [126. 159. 190.]]

 [[ 69.  54.  51.]
  [ 67.  52.  49.]
  [ 68.  54.  53.]
  ...
  [132. 162. 190.]
  [116. 150. 177.]
  [112. 145. 176.]]]


In [4]:
# Preprocess input
for elem in data:
    elem = preprocess_input(elem)

In [5]:
# View first element of data
print(data[0])

[[[ 75.32       52.221      27.060997 ]
  [ 76.32       53.221      28.060997 ]
  [ 78.32       55.221      30.060997 ]
  ...
  [ 49.32        4.2210007  -6.939003 ]
  [ 48.32        3.2210007  -7.939003 ]
  [ 49.32        2.2210007 -10.939003 ]]

 [[ 76.32       53.221      28.060997 ]
  [ 77.32       54.221      29.060997 ]
  [ 79.32       56.221      31.060997 ]
  ...
  [ 50.32        5.2210007  -5.939003 ]
  [ 49.32        4.2210007  -6.939003 ]
  [ 49.32        2.2210007 -10.939003 ]]

 [[ 78.32       55.221      30.060997 ]
  [ 79.32       56.221      31.060997 ]
  [ 80.32       57.221      32.060997 ]
  ...
  [ 52.32        7.2210007  -3.939003 ]
  [ 51.32        6.2210007  -4.939003 ]
  [ 51.32        4.2210007  -8.939003 ]]

 ...

 [[-56.68      -64.779     -54.939003 ]
  [-57.68      -65.779     -55.939003 ]
  [-55.68      -62.779     -50.939003 ]
  ...
  [ 20.32       57.221      98.061    ]
  [ 14.32       55.221      95.061    ]
  [ 23.32       63.221     107.061    ]]

 [